<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="abinca" lastModifiedBy="abinca" checksumTest="true" creationDate="27/09/2016 16:55:55 +0300" engineType="DML" lastModifiedDate="27/09/2016 16:56:24 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/bd.dmlflw"/>
   </mappingInformations>
</project>